### ISSUE TITLE
Run this code from Napa cloud.

### ISSUE THREAD

**Issue by ShrutiD** [OfficeDev/Office-Add-in-JavaScript-WebApiService#1]
Can't we run this code using NAPA cloud?

**Comment by jamescro** [comment]
This sample is set up to work with a local Office client app and a web service running on the same machine, so it probably won't work on Napa cloud.

**Comment by Markomxx** [comment]
Getting the error message 0x80131040 when trying to start: Could not load file or assembly 'DocumentFormat.OpenXml'. Cleaning and rebuilding does not help nor clearing the bin folders.
